from django.conf.urls import patterns, url

from Inventory import views

urlpatterns = patterns('',
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page' : '../login'}, name='logout'),
    url(r'^login_home/$', views.login_home, name='login_home'),
    url(r'^transaction$', views.calculate_transaction, name='transaction'),
	url(r'^transaction/add_transaction$', views.add_transaction, name='add_transaction'),
	url(r'^transaction/add_cachier_transaction$', views.add_cachier_transaction, name='add_cachier_transaction'),
	url(r'^transaction/cachier_transaction$', views.cachier_transaction, name='cachier_transaction'),
	url(r'^display$', views.price_display, name='display'),
	url(r'^home$', views.home_page, name='home'),
	url(r'^sync$', views.sync_function, name='sync'),
	url(r'^product$', views.product_list, name='product'),
	url(r'^product/(\d+)/edit_product$', views.edit_product, name='edit_product'),
	url(r'^product/update_product$', views.update_product, name='update_product'),
	url(r'^inventory$', views.inventory_list, name='inventory'),
	url(r'^inventory/update_inventory$', views.update_inventory, name='update_inventory'),
	url(r'^inventory/(\d+)/(\d+)/edit_inventory$', views.edit_inventory, name='edit_inventory'),
	url(r'^dispay/(\d+)/(\d+)/(\d+)/edit_display$', views.edit_display, name='edit_display'),
	url(r'^returnPrice$', views.return_price, name='return_price'),
	url(r'^getPrice$', views.get_price, name='get_price'),
	url(r'^checkId$', views.checkId, name='checkId'),
	url(r'^deductInventory$', views.deduct_inventory, name='deduct_inventory'),
	url(r'^saveTransaction$', views.save_transaction, name='save_transaction'),
	url(r'^restock$',views.restock_qty,name='restock_qty'),	
	url(r'^addQuantity$', views.add_qty_back, name='add_qty_back'),	
	url(r'^check_display$', views.check_display, name='check_display'),	
	url(r'^write_to_display$', views.write_to_display, name='write_to_display'),	
	url(r'^setDisplayID$', views.setDisplayID, name='setDisplayID'),
	url(r'^sync/transaction_sync$', views.transaction_sync, name='transaction_sync'),
	url(r'^sync/inventory_sync$', views.inventory_sync, name='inventory_sync'),
	url(r'^sync/request_details_sync$', views.request_details_sync, name='request_details_sync'),
	url(r'^sync/product_sync$', views.product_sync, name='product_sync'),
	url(r'^sync/pull_product_from_hq$', views.pull_product_from_hq, name='pull_product_from_hq'),
	url(r'^sync/pull_inventory_from_hq$', views.pull_inventory_from_hq, name='pull_inventory_from_hq'),
	url(r'^sync/update_perishable_price$', views.update_perishable_price, name='update_perishable_price'),
	url(r'^sync/update_nonperishable_price$', views.update_nonperishable_price, name='update_nonperishable_price'),
)