ADD_TO_PRICE_BUFFER:
			PUSH BX
			MOV BX, DS:COUNTER3
			MOV DS:PRICE_BUFF[BX], AL
		    INC BX
			MOV DS:COUNTER3, BX
			POP BX
			JMP S_RET

SHOW_PRICE:
		  PUSH BX
		  MOV BX, DS:COUNTER3
          MOV AL, DS:PRICE_BUFFER[BX]
		  PUSH BX
		  MOV BX,DS:DISPLAY_COUNTER
		  MOV DS:LED_DISPLAY[BX],AL
		  INC BX
		  MOV DS:DISPLAY_COUNTER,BX
		  POP BX
		  DEC BX
		  CMP BX,0H
		  JE POP_P
		  LOOP SHOW_PRICE
		  		
FLAG_DECIDE:
		CMP AL,'*'
		JE SEND_DATA
		JNE ADD_TO_QTBUFFER

SEND_DATA:
			PUSH BX
			XOR BX, BX
			
LABEL_LOOP:	MOV AL,DS:BARQTYPRICE_BUFF[BX]
			CALL FAR PTR PRINT_CHAR
		    CMP BX, DS:COUNTER2
			JE SEND_STAR
			INC BX
			LOOP LABEL_LOOP

SEND_STAR:
		MOV AL, '*'
		CALL FAR PTR PTR_CHAR
		JMP POP_P
		
ADD_TO_QTBUFFER:
			PUSH BX
			MOV BX, DS:COUNTER2
			MOV DS:BARQTYPRICE_BUFF[BX], AL
		    INC BX
			MOV DS:COUNTER2, BX
			POP BX
			JMP S_RET	

SET_FLAG:
		MOV AL, '!'
		CALL FAR PTR PRINT_CHAR
		MOV DS:FLAG, 0H	
		MOV DS:DFLAG, 0H
		MOV	COUNTER,0H
		MOV COUNTER2,0H
		MOV DISPLAY_COUNTER,0H
		MOV COUNTER3,0H
		JMP S_RET

ADD_TO_BUFFER:
			PUSH BX
			MOV BX, DS:COUNTER
			MOV DS:CASHIERID_BUFF[BX], AL
		    INC BX
			MOV DS:COUNTER, BX
			POP BX
			JMP S_RET

CHECK_CASHIER:
		PUSH BX
		MOV DS:DFLAG, 01H
		CMP DS:COUNTER, 04H
		JNE POP_P
		MOV DS:COUNTER, 00H
		XOR BX, BX
		MOV AL, DS:CASHIERID_BUFF[BX]
		CMP Al,31H
		JNE POP_P
		INC BX
		MOV AL, DS:CASHIERID_BUFF[BX]
		CMP Al,31H
		JNE POP_P
		INC BX
		MOV AL, DS:CASHIERID_BUFF[BX]
		CMP Al,31H
		JNE POP_P
		INC BX
		MOV AL, DS:CASHIERID_BUFF[BX]
		CMP Al,31H
		JNE POP_P
		MOV AL,'@'
		CALL FAR PTR PRINT_CHAR
		MOV DS:FLAG, 01H
		MOV AL, DS:FLAG
		CALL FAR PTR PRINT_CHAR
		JMP POP_P
				
POP_P:
		POP BX
		JMP S_RET

		
ERROR_SHOW:	
	mov BX, 0H
	mov DS:LED_DISPLAYS[BX], 2FH
	inc BX
	mov DS:LED_DISPLAYS[BX], 24H
	inc BX
	mov DS:LED_DISPLAYS[BX], 24H
	inc BX
	mov DS:LED_DISPLAYS[BX], 3CH
	inc BX
	mov DS:LED_DISPLAYS[BX], 24H
	inc BX
	mov DS:LED_DISPLAYS[BX], 00H
	jmp S_RET